---
title: "My Website"
author: "Dr. Elizabeth Figus, BA, MA, Etc."
date: "November 29, 2017"
output: html_document
editor_options: 
  chunk_output_type: inline
---
```{r, cache = TRUE, echo = FALSE}
escapement <- read.csv("knb.92020.1.csv", stringsAsFactors = FALSE)
# escapement
# names(escapement)
```

```{r, echo = FALSE}
library(tidyr)
library(dplyr)
library(leaflet)
library(ggplot2)
library(DT)
```

# Median annual escapement by species

```{r}
# median annual esc. by species
# this is an example of 'dplyr' dee-pliar pipes to reformat the dataset
median_esc <- escapement %>%
  separate(sampleDate, c("Year", "Month", "Day"), sep = "-") %>%
  group_by(Species, Location, Year) %>%
  summarize(escapement = sum(DailyCount, na.rm = TRUE)) %>%
  group_by(Species) %>%
  summarize(Median_Escapement = median(escapement))

median_esc
```

```{r}
ggplot(median_esc, aes(Species, Median_Escapement)) +
  geom_col() +
  theme_classic() +
  coord_flip()
```

```{r}
datatable(median_esc)
```

```{r}
locations <- escapement %>%
  distinct(Location, Latitude, Longitude) %>%
  drop_na()

#recreating GoogleMaps inside the document; you could use a MapBox tile layer, or make your own to use
leaflet(locations) %>%
  addTiles() %>%
  addMarkers(~ -abs(Longitude), ~ Latitude, popup = ~ Location)
```




